### ISSUE TITLE
[question] If my streaming function is also getting data from a stream, is there any way to save data when the function is done streaming just before completing its execution?

### ISSUE THREAD

**Issue by aej11a** [ejizba/azure-functions-nodejs-stream#3]
Very wordy title but basically:

1. my Azure Function makes some DB calls and formats data
2. then it calls OpenAI's API with stream: true
3. then returns the stream, so the response streams 

Is there any way to "do something" at the end of the stream, before the function finishes?

In express, for example, you can write the stream to the response object, then your code continues as normal after the stream. But since Azure seems to require us to return the stream, this seems much more difficult.

**Comment by ejizba** [comment]
Moved to https://github.com/Azure/azure-functions-nodejs-library/issues/233

**Comment by ejizba** [comment]
I don't have a quick answer, but we'll look into it
